### PR TITLE
Adding responsive design to sidebar

### PR DESCRIPTION
**Pull request by pczern**

### CODE REVIEW

**Comment by pczern** [comment]
The webpage before had problems with resizing

**Comment by gtomitsuka** [comment]
Since I don't see anything that needs review, I believe this merge will be pretty straightforward. Could you please also look at the v1.5 branch, too? My work is being there.

**Comment by pczern** [comment]
Do you mean syncing? (I am new to GitHub)

2015-02-07 10:52 GMT+01:00 Gabriel Tomitsuka notifications@github.com:

> Merged #15 https://github.com/gtomitsuka/montreus-chat/pull/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gtomitsuka/montreus-chat/pull/15#event-231927314.

## 

http://de.linkedin.com/pub/philipp-czernitzki/94/658/84
Google+ https://plus.google.com/u/0/101073241749567186183/posts/p/pub
Twitter https://twitter.com/speedDeveloper
Webseite: API-Developers http://api-developers.com

**Comment by gtomitsuka** [comment]
Yes, please sync your master with master. It adds a public/ folder for files that will be public.

**Comment by pczern** [comment]
How do I do that?

**Pull request merged**
